name: block-preset-from-image
description: "이미지를 분석하여 super-editor-v2 block preset을 생성합니다. 대화형 워크플로우로 구조를 완성합니다."
author: "BMad"

# Config
config_source: "{project-root}/.bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# ============================================================
# Image Analysis Settings
# ============================================================

# ⚠️ Auto Layout First 원칙
# Hero 블록을 제외한 모든 블록은 Auto Layout (layout.mode: 'auto')을 기본으로 사용
# 장식 요소나 지원하기 어려운 디자인에서만 absolute 사용
layout_strategy:
  default_mode: auto  # Hero 제외 모든 블록 기본값
  hero_mode: absolute  # Hero 블록만 absolute
  exceptions:
    - decoration_elements: absolute  # 배경 장식 (sparkle, leaf, ornament)
    - map_elements: absolute  # 지도/캐러셀 등 외부 라이브러리 영역
    - gallery_carousel: absolute  # 갤러리 캐러셀

# 이미지 분석 시 추출할 정보
analysis_targets:
  layout:
    - layout_mode: "Auto Layout (auto) vs Absolute (absolute) 결정"
    - direction: "vertical | horizontal (Auto Layout 시)"
    - element_hierarchy: "요소들의 시각적 계층구조"
    - spacing_pattern: "gap, padding 패턴"
    - decoration_elements: "장식 요소 (absolute로 처리)"

  typography:
    - font_family_role: "display/heading/body 3-Family 분류"
    - text_hierarchy: "제목/본문/캡션 등 텍스트 계층"
    - text_alignment: "텍스트 정렬 방식"

  visual_style:
    - color_system_type: "1컬러 (P-S-T) vs 2컬러 (P-S-T+A)"
    - primary_color: "Primary (P) - 제목, 강조"
    - accent_color: "Accent (A) - 버튼, 아이콘 (2컬러 시)"
    - mood: "전체적인 분위기 (minimal, elegant, romantic 등)"

  content_mapping:
    - bindable_elements: "데이터 바인딩 가능한 요소"
    - static_elements: "정적 디자인 요소"
    - interactive_elements: "버튼, 링크 등 인터랙티브 요소"

# 사용 가능한 BlockType (순서 = 일반적인 청첩장 배치 순서)
available_block_types:
  - hero              # 히어로 (메인 사진, 이름, 날짜)
  - greeting-parents  # 인사말/혼주정보
  - profile           # 신랑신부 소개/인터뷰
  - calendar          # 예식일시 (달력/D-day)
  - gallery           # 갤러리 (사진/영상)
  - rsvp              # 참석 여부
  - location          # 오시는길 (지도/교통)
  - notice            # 공지사항/안내
  - account           # 축의금 계좌
  - message           # 방명록
  - ending            # 축하화환/공유/엔딩
  - music             # BGM 컨트롤
  - loading           # 로딩 화면
  - custom            # 사용자 정의 블록

# 블록 카테고리 (UI 그룹핑/AI 맥락용, 프리셋 구조와 무관)
block_categories:
  - name: "히어로"
    types: [hero]
  - name: "인사말/혼주정보"
    types: [greeting-parents]
  - name: "신랑신부 소개/인터뷰"
    types: [profile]
  - name: "예식일시"
    types: [calendar]
  - name: "갤러리"
    types: [gallery]
  - name: "RSVP"
    types: [rsvp]
  - name: "오시는길"
    types: [location]
  - name: "공지사항"
    types: [notice]
  - name: "축의금 계좌"
    types: [account]
  - name: "방명록"
    types: [message]
  - name: "축하화환/공유/엔딩"
    types: [ending]
  - name: "기타기능"
    types: [music, loading, custom]

# 사용 가능한 ElementType
available_element_types:
  - text
  - image
  - shape
  - button
  - icon
  - divider
  - map
  - calendar
  - group     # 중첩 레이아웃 (Auto Layout 컨테이너)

# ============================================================
# P-S-T 컬러 시스템
# ============================================================

# 컬러 시스템 타입
color_system:
  one_color_pst:
    description: "1컬러 시스템 - Primary만 입력, S/T 자동 계산"
    input: ["Primary (P)"]
    auto_generated: ["Secondary (S)", "Tertiary (T)"]
    formula:
      S: "H 유지, S×0.5, L=97%"
      T: "H 유지, S×0.9, L=85%"

  two_color_psta:
    description: "2컬러 시스템 - Primary + Accent 입력, S/T 자동 계산"
    input: ["Primary (P)", "Accent (A)"]
    auto_generated: ["Secondary (S)", "Tertiary (T)"]
    formula:
      S: "P에서 L=97%"
      T: "P에서 L=85%"

# 시맨틱 토큰 매핑 (17개)
semantic_color_tokens:
  background:
    - name: "bg-page"
      description: "페이지 전체 배경"
      default: "#FFFFFF"
    - name: "bg-section"
      description: "기본 섹션 배경"
      default: "#FFFFFF"
    - name: "bg-section-alt"
      description: "대체 섹션 배경"
      default: "#FFFFFF"
    - name: "bg-card"
      description: "카드 배경"
      mapping: "Secondary (S)"
    - name: "bg-overlay"
      description: "오버레이/모달 딤"
      default: "rgba(0,0,0,0.4)"

  foreground:
    - name: "fg-default"
      description: "기본 본문 텍스트"
      default: "#1A1A1A"
    - name: "fg-muted"
      description: "보조 텍스트, 캡션"
      default: "#6B7280"
    - name: "fg-emphasis"
      description: "제목, 강조 텍스트"
      mapping: "Primary (P)"
    - name: "fg-inverse"
      description: "반전 배경 위 텍스트"
      default: "#FFFFFF"
    - name: "fg-on-accent"
      description: "액센트 버튼 위 텍스트"
      default: "#FFFFFF"

  accent:
    - name: "accent-default"
      description: "아이콘, 버튼, 활성 탭"
      mapping_1color: "Primary (P)"
      mapping_2color: "Accent (A)"
    - name: "accent-hover"
      description: "호버 상태"
      mapping_1color: "Tertiary (T)"
      mapping_2color: "A (L+10%)"
    - name: "accent-active"
      description: "클릭/활성 상태"
      mapping_1color: "Primary (P)"
      mapping_2color: "A (L-5%)"
    - name: "accent-secondary"
      description: "보조 강조"
      mapping: "Tertiary (T)"

  border:
    - name: "border-default"
      description: "기본 테두리"
      default: "#E5E7EB"
    - name: "border-emphasis"
      description: "강조 테두리"
      mapping_1color: "Primary (P)"
      mapping_2color: "Accent (A)"
    - name: "border-muted"
      description: "연한 테두리"
      default: "#F3F4F6"

# 테마 프리셋 ID
theme_preset_ids:
  one_color:
    - simple-pink      # P: #EF90CB
    - simple-coral     # P: #EC8A87
    - simple-blue      # P: #002BFF
  classic:
    - minimal-light
    - classic-ivory
    - classic-gold
  modern:
    - modern-mono
  romantic:
    - romantic-blush
    - romantic-garden
  special:
    - photo-adaptive   # 사진에서 색상 추출

# ============================================================
# 3-Family 타이포그래피 시스템
# ============================================================

# 폰트 역할
typography_tokens:
  font_families:
    - name: "font-display"
      description: "히어로/인트로용 (예술적, 장식적)"
      css_var: "var(--font-display)"
    - name: "font-heading"
      description: "섹션 제목용 (명조/세리프 계열)"
      css_var: "var(--font-heading)"
    - name: "font-body"
      description: "섹션 본문용 (고딕/산세리프 계열)"
      css_var: "var(--font-body)"

  font_weights:
    - name: "font-weight-display"
      css_var: "var(--font-weight-display)"
    - name: "font-weight-heading"
      css_var: "var(--font-weight-heading)"
    - name: "font-weight-body"
      css_var: "var(--font-weight-body)"

  # ⚠️ fontSize는 number (px 단위)로 프리셋에 저장
  # 렌더링 시 pxToRem()으로 자동 변환 → 접근성 지원 (사용자 시스템 폰트 설정 존중)
  # 아래는 참고용 px 값
  type_scale_reference:
    - name: "xs"
      px: 12
      description: "캡션, 주석"
    - name: "sm"
      px: 14
      description: "보조 텍스트"
    - name: "base"
      px: 16
      description: "본문 기본"
    - name: "lg"
      px: 18
      description: "본문 강조"
    - name: "xl"
      px: 20
      description: "소제목"
    - name: "2xl"
      px: 24
      description: "섹션 제목"
    - name: "3xl"
      px: 30
      description: "블록 제목"
    - name: "4xl"
      px: 36
      description: "히어로 제목"

# 타이포그래피 프리셋 ID
typography_preset_ids:
  classic:
    - classic-elegant      # Playfair + Noto Serif
    - classic-traditional  # Cinzel + Nanum Myeongjo
    - classic-romantic     # Cormorant + Gowun Batang
  modern:
    - modern-minimal       # Montserrat + Pretendard
    - modern-clean         # Inter + Noto Sans
    - modern-geometric     # Poppins + Pretendard
  romantic:
    - romantic-script      # Great Vibes + Gowun Batang
    - romantic-italian     # Italianno + Noto Serif
    - romantic-soft        # Pinyon Script + Hahmlet
  natural:
    - natural-handwritten  # High Summit + 마포금빛나루
    - natural-brush        # Alex Brush + 나눔붓글씨
    - natural-warm         # Dancing Script + 고운돋움
    - natural-witty

# ============================================================
# Source and target references
# ============================================================
v2_types: "{project-root}/src/lib/super-editor-v2/schema/types.ts"
v2_presets: "{project-root}/src/lib/super-editor-v2/presets"
block_presets_file: "{v2_presets}/block-presets.ts"

# Input file patterns for context loading
input_file_patterns:
  v2_schema:
    description: "v2 schema types for block structure"
    whole: "{v2_types}"
    load_strategy: "FULL_LOAD"
  existing_presets:
    description: "Existing block presets for reference"
    sharded: "{v2_presets}/*.ts"
    load_strategy: "FULL_LOAD"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/block-preset-from-image"
instructions: "{installed_path}/instructions.md"

# Output will be appended to or create new file
output_mode: "conversational"  # 대화형 - 파일 생성은 최종 단계에서

standalone: true
